#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copy this file to MPD_HOOKER_DIR/hooks/bitrate where MPD_HOOKER_DIR is
# ~/.mpdhooker by default and make it executable.

# Example bitrate change hook
old="$1"
new="$2"

echo ">>> Bitrate changed from ${old}Hz to ${new}Hz"
