#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copy this file to MPD_HOOKER_DIR/hooks/crossfade where MPD_HOOKER_DIR is
# ~/.mpdhooker by default and make it executable.

# Example crossfade change hook
old="$1"
new="$2"

echo ">>> Crossfade changed from $old to $new"
