#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copy this file to MPD_HOOKER_DIR/hooks/elapsed where MPD_HOOKER_DIR is
# ~/.mpdhooker by default and make it executable.

# Example elapsed time change hook
old="$1"
new="$2"
total="$3"

echo ">>> Elapsed time changed from $old to $new (total: $total)"
