#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copy this file to MPD_HOOKER_DIR/hooks/repeat where MPD_HOOKER_DIR is
# ~/.mpdhooker by default and make it executable.

# Example repeat change hook
if [[ $1 == 1 ]]; then
    echo ">>> Repeat mode on"
else
    echo ">>> Repeat mode off"
fi
