#!/bin/sh
# vim: set sw=4 et sts=4 tw=80 :
# Copy this file to MPD_HOOKER_DIR/hooks/state where MPD_HOOKER_DIR is
# ~/.mpdhooker by default and make it executable.

# Example state change hook
old="$1"
new="$2"

echo ">>> State change from $old to $new"
